github: [octocat, surftocat]
patreon: octocat
tidelift: npm/octo-package
custom: ["https://www.paypal.me/octocat", octocat.com]
issuehunt: octocat
ko_fi: octocat
open_collective: webpack
community_bridge: octo-cat
otechie: octocat
